### ISSUE TITLE
[FR] Support nested fields in ront-matter

### ISSUE THREAD

**Issue by racy2020** [zsviczian/excalibrain#84]
When I use front-matter, I find that Excalibrain only perceives flat fields, and it can not see nested fields.
If all fields are flat, it is difficult to manage and view.
eg:
**flat**
```yaml
my-father: ["[[father]]"]
my-mother: ["[[mother]]"]
my-child: ["[[child1]]", "[[child2]]", "[[child3]]"]
my-cat: ["[[cat]]"]
my-dog: ["[[dog]]"]
```
![image](https://user-images.githubusercontent.com/70854078/185741669-e1cd22ff-dd52-4ee2-8cd4-b04dcb206d94.png)

**nested**
```yaml
relation-link:
 - parents:
   - my-father: ["[[father]]"]
   - my-mother: ["[[mother]]"]
 - children:
   - my-child: ["[[child1]]", "[[child2]]", "[[child3]]"]
 - friends:
   - my-cat: ["[[cat]]"]
   - my-dog: ["[[dog]]"]
```
![image](https://user-images.githubusercontent.com/70854078/185741733-e2c0b094-6cb0-4af3-9fd3-7b77472b4bc7.png)

Compared with the current state, I think it may slightly increase the performance consumption. Therefore, I think it is possible to provide a setting item to only parse the nested fields within the fields specified in it. This field is set by the user ( such as relation-link, ontology-section, etc.)
